name: deploy2github

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build the Project
        run: bun run build

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          # Set the source branch for deployment (change if needed)
          branch: ${{ github.ref }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # Upload the built project folder
          source: ./dist
