name: Update Dependencies
on:
  schedule:
    - cron: '0 5 * * 3,6' #At 05:00 on Wednesday and Saturday.
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v1

      - name: Update dependencies
        run: |
          bunx taze -w
          bun install

      - name: Commit updates
        run: |
         git config user.name "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add .
         git commit -m "chore(deps): bump dependencies"
         git push